name: 'Python Build'
on:
  pull_request:
    paths:
      - 'pygoat/**'
    branches: [main]

  push:
    paths:
      - 'pygoat/**'
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Build
        run: |
          python -m pip install --no-cache-dir pip==22.0.4
          pip install --no-cache-dir -r requirements.txt
        working-directory: ./pygoat
